//! Design values extracted from the signed-off prototype.
//!
         //! GENERATED by `gate-fidelity extract`. Do not edit: a hand edit is a fork of
         //! the design system, and the off-token lint will reject any value that is not
         //! here.

/// `chrome-breadcrumbs` from mockups/assets.md:123
pub const CHROME_BREADCRUMBS: &str = "24px";

/// `chrome-dock-header` from mockups/assets.md:123
pub const CHROME_DOCK_HEADER: &str = "30px";

/// `chrome-dock-tab-strip` from mockups/assets.md:123
pub const CHROME_DOCK_TAB_STRIP: &str = "28px";

/// `chrome-rail-width` from mockups/assets.md:123
pub const CHROME_RAIL_WIDTH: &str = "44px";

/// `chrome-remote-banner` from mockups/assets.md:123
pub const CHROME_REMOTE_BANNER: &str = "26px";

/// `chrome-status-bar` from mockups/assets.md:123
pub const CHROME_STATUS_BAR: &str = "26px";

/// `chrome-tab-strip` from mockups/assets.md:123
pub const CHROME_TAB_STRIP: &str = "34px";

/// `chrome-toolbar` from mockups/assets.md:123
pub const CHROME_TOOLBAR: &str = "46px";

/// `color-accent` from mockups/_ds/nocturne-85583080-aa1c-49ca-9469-934d1899d563/styles.css:8
pub const COLOR_ACCENT: &str = "#9184d9";

/// `color-accent-100` from mockups/_ds/nocturne-85583080-aa1c-49ca-9469-934d1899d563/styles.css:31
pub const COLOR_ACCENT_100: &str = "#f5f4ff";

/// `color-accent-2` from mockups/_ds/nocturne-85583080-aa1c-49ca-9469-934d1899d563/styles.css:15
pub const COLOR_ACCENT_2: &str = "#a7a1db";

/// `color-accent-2-100` from mockups/_ds/nocturne-85583080-aa1c-49ca-9469-934d1899d563/styles.css:41
pub const COLOR_ACCENT_2_100: &str = "#f5f4ff";

/// `color-accent-2-200` from mockups/_ds/nocturne-85583080-aa1c-49ca-9469-934d1899d563/styles.css:42
pub const COLOR_ACCENT_2_200: &str = "#e7e5fe";

/// `color-accent-2-300` from mockups/_ds/nocturne-85583080-aa1c-49ca-9469-934d1899d563/styles.css:43
pub const COLOR_ACCENT_2_300: &str = "#d2cefd";

/// `color-accent-2-400` from mockups/_ds/nocturne-85583080-aa1c-49ca-9469-934d1899d563/styles.css:44
pub const COLOR_ACCENT_2_400: &str = "#b5afe8";

/// `color-accent-2-500` from mockups/_ds/nocturne-85583080-aa1c-49ca-9469-934d1899d563/styles.css:45
pub const COLOR_ACCENT_2_500: &str = "#9690c9";

/// `color-accent-2-600` from mockups/_ds/nocturne-85583080-aa1c-49ca-9469-934d1899d563/styles.css:46
pub const COLOR_ACCENT_2_600: &str = "#7972a9";

/// `color-accent-2-700` from mockups/_ds/nocturne-85583080-aa1c-49ca-9469-934d1899d563/styles.css:47
pub const COLOR_ACCENT_2_700: &str = "#5c5783";

/// `color-accent-2-800` from mockups/_ds/nocturne-85583080-aa1c-49ca-9469-934d1899d563/styles.css:48
pub const COLOR_ACCENT_2_800: &str = "#423e5d";

/// `color-accent-2-900` from mockups/_ds/nocturne-85583080-aa1c-49ca-9469-934d1899d563/styles.css:49
pub const COLOR_ACCENT_2_900: &str = "#2b293a";

/// `color-accent-200` from mockups/_ds/nocturne-85583080-aa1c-49ca-9469-934d1899d563/styles.css:32
pub const COLOR_ACCENT_200: &str = "#e7e5fe";

/// `color-accent-300` from mockups/_ds/nocturne-85583080-aa1c-49ca-9469-934d1899d563/styles.css:33
pub const COLOR_ACCENT_300: &str = "#d2cefd";

/// `color-accent-400` from mockups/_ds/nocturne-85583080-aa1c-49ca-9469-934d1899d563/styles.css:34
pub const COLOR_ACCENT_400: &str = "#b5abfc";

/// `color-accent-500` from mockups/_ds/nocturne-85583080-aa1c-49ca-9469-934d1899d563/styles.css:35
pub const COLOR_ACCENT_500: &str = "#968ae0";

/// `color-accent-600` from mockups/_ds/nocturne-85583080-aa1c-49ca-9469-934d1899d563/styles.css:36
pub const COLOR_ACCENT_600: &str = "#796cbf";

/// `color-accent-700` from mockups/_ds/nocturne-85583080-aa1c-49ca-9469-934d1899d563/styles.css:37
pub const COLOR_ACCENT_700: &str = "#5d5294";

/// `color-accent-800` from mockups/_ds/nocturne-85583080-aa1c-49ca-9469-934d1899d563/styles.css:38
pub const COLOR_ACCENT_800: &str = "#423a6a";

/// `color-accent-900` from mockups/_ds/nocturne-85583080-aa1c-49ca-9469-934d1899d563/styles.css:39
pub const COLOR_ACCENT_900: &str = "#2b2741";

/// `color-bg` from mockups/_ds/nocturne-85583080-aa1c-49ca-9469-934d1899d563/styles.css:5
pub const COLOR_BG: &str = "#161826";

/// `color-divider` from mockups/_ds/nocturne-85583080-aa1c-49ca-9469-934d1899d563/styles.css:17
pub const COLOR_DIVIDER: &str = "color-mix(in srgb, #e9e9ed 16%, transparent)";

/// `color-neutral-100` from mockups/_ds/nocturne-85583080-aa1c-49ca-9469-934d1899d563/styles.css:21
pub const COLOR_NEUTRAL_100: &str = "#f3f5fe";

/// `color-neutral-200` from mockups/_ds/nocturne-85583080-aa1c-49ca-9469-934d1899d563/styles.css:22
pub const COLOR_NEUTRAL_200: &str = "#e4e7f5";

/// `color-neutral-300` from mockups/_ds/nocturne-85583080-aa1c-49ca-9469-934d1899d563/styles.css:23
pub const COLOR_NEUTRAL_300: &str = "#cfd3e5";

/// `color-neutral-400` from mockups/_ds/nocturne-85583080-aa1c-49ca-9469-934d1899d563/styles.css:24
pub const COLOR_NEUTRAL_400: &str = "#b2b6ca";

/// `color-neutral-500` from mockups/_ds/nocturne-85583080-aa1c-49ca-9469-934d1899d563/styles.css:25
pub const COLOR_NEUTRAL_500: &str = "#9397ab";

/// `color-neutral-600` from mockups/_ds/nocturne-85583080-aa1c-49ca-9469-934d1899d563/styles.css:26
pub const COLOR_NEUTRAL_600: &str = "#75798c";

/// `color-neutral-700` from mockups/_ds/nocturne-85583080-aa1c-49ca-9469-934d1899d563/styles.css:27
pub const COLOR_NEUTRAL_700: &str = "#595d6c";

/// `color-neutral-800` from mockups/_ds/nocturne-85583080-aa1c-49ca-9469-934d1899d563/styles.css:28
pub const COLOR_NEUTRAL_800: &str = "#3f424d";

/// `color-neutral-900` from mockups/_ds/nocturne-85583080-aa1c-49ca-9469-934d1899d563/styles.css:29
pub const COLOR_NEUTRAL_900: &str = "#292b31";

/// `color-section` from mockups/_ds/nocturne-85583080-aa1c-49ca-9469-934d1899d563/styles.css:57
pub const COLOR_SECTION: &str = "#262a60";

/// `color-section-ghost` from mockups/_ds/nocturne-85583080-aa1c-49ca-9469-934d1899d563/styles.css:59
pub const COLOR_SECTION_GHOST: &str = "#4c5397";

/// `color-section-glow` from mockups/_ds/nocturne-85583080-aa1c-49ca-9469-934d1899d563/styles.css:58
pub const COLOR_SECTION_GLOW: &str = "#353b80";

/// `color-surface` from mockups/_ds/nocturne-85583080-aa1c-49ca-9469-934d1899d563/styles.css:6
pub const COLOR_SURFACE: &str = "#232532";

/// `color-text` from mockups/_ds/nocturne-85583080-aa1c-49ca-9469-934d1899d563/styles.css:7
pub const COLOR_TEXT: &str = "#e9e9ed";

/// `font-body` from mockups/_ds/nocturne-85583080-aa1c-49ca-9469-934d1899d563/styles.css:63
pub const FONT_BODY: &str = "\"Inter\", system-ui, sans-serif";

/// `font-heading` from mockups/_ds/nocturne-85583080-aa1c-49ca-9469-934d1899d563/styles.css:61
pub const FONT_HEADING: &str = "\"Inter\", system-ui, sans-serif";

/// `font-heading-weight` from mockups/_ds/nocturne-85583080-aa1c-49ca-9469-934d1899d563/styles.css:62
pub const FONT_HEADING_WEIGHT: &str = "500";

/// `manifest-comments-75798c` from mockups/assets.md:111
pub const MANIFEST_COMMENTS_75798C: &str = "#75798c";

/// `manifest-error-diagnostics-breakpoint-d4736a` from mockups/assets.md:95
pub const MANIFEST_ERROR_DIAGNOSTICS_BREAKPOINT_D4736A: &str = "#d4736a";

/// `manifest-function-and-method-e4e7f5` from mockups/assets.md:107
pub const MANIFEST_FUNCTION_AND_METHOD_E4E7F5: &str = "#e4e7f5";

/// `manifest-go-file-tint-8fb3a5` from mockups/assets.md:98
pub const MANIFEST_GO_FILE_TINT_8FB3A5: &str = "#8fb3a5";

/// `manifest-identifiers-numbers-terminal-cfd3e5` from mockups/assets.md:108
pub const MANIFEST_IDENTIFIERS_NUMBERS_TERMINAL_CFD3E5: &str = "#cfd3e5";

/// `manifest-inlay-hints-virtual-e6e6ea` from mockups/assets.md:113
pub const MANIFEST_INLAY_HINTS_VIRTUAL_E6E6EA: &str = "#e6e6ea";

/// `manifest-keywords-annotations-toml-b5abfc` from mockups/assets.md:105
pub const MANIFEST_KEYWORDS_ANNOTATIONS_TOML_B5ABFC: &str = "#b5abfc";

/// `manifest-line-numbers-595d6c` from mockups/assets.md:112
pub const MANIFEST_LINE_NUMBERS_595D6C: &str = "#595d6c";

/// `manifest-modal-scrim-base-0d0f18` from mockups/assets.md:99
pub const MANIFEST_MODAL_SCRIM_BASE_0D0F18: &str = "#0d0f18";

/// `manifest-punctuation-operators-9397ab` from mockups/assets.md:110
pub const MANIFEST_PUNCTUATION_OPERATORS_9397AB: &str = "#9397ab";

/// `manifest-string-literals-b2b6ca` from mockups/assets.md:109
pub const MANIFEST_STRING_LITERALS_B2B6CA: &str = "#b2b6ca";

/// `manifest-success-tests-passed-7fa98f` from mockups/assets.md:97
pub const MANIFEST_SUCCESS_TESTS_PASSED_7FA98F: &str = "#7fa98f";

/// `manifest-types-classes-doc-d2cefd` from mockups/assets.md:106
pub const MANIFEST_TYPES_CLASSES_DOC_D2CEFD: &str = "#d2cefd";

/// `manifest-warning-modified-file-c9a96a` from mockups/assets.md:96
pub const MANIFEST_WARNING_MODIFIED_FILE_C9A96A: &str = "#c9a96a";

/// `radius-lg` from mockups/_ds/nocturne-85583080-aa1c-49ca-9469-934d1899d563/styles.css:74
pub const RADIUS_LG: &str = "14px";

/// `radius-md` from mockups/_ds/nocturne-85583080-aa1c-49ca-9469-934d1899d563/styles.css:73
pub const RADIUS_MD: &str = "8px";

/// `radius-sm` from mockups/_ds/nocturne-85583080-aa1c-49ca-9469-934d1899d563/styles.css:72
pub const RADIUS_SM: &str = "4px";

/// `shadow-lg` from mockups/_ds/nocturne-85583080-aa1c-49ca-9469-934d1899d563/styles.css:80
pub const SHADOW_LG: &str = "0 0 0 1px #9397ab, 0 16px 40px rgba(0,0,0,0.65)";

/// `shadow-md` from mockups/_ds/nocturne-85583080-aa1c-49ca-9469-934d1899d563/styles.css:79
pub const SHADOW_MD: &str = "0 0 0 1px #595d6c, 0 6px 18px rgba(0,0,0,0.55)";

/// `shadow-sm` from mockups/_ds/nocturne-85583080-aa1c-49ca-9469-934d1899d563/styles.css:78
pub const SHADOW_SM: &str = "0 0 0 1px #3f424d";

/// `space-1` from mockups/_ds/nocturne-85583080-aa1c-49ca-9469-934d1899d563/styles.css:65
pub const SPACE_1: &str = "2.8px";

/// `space-2` from mockups/_ds/nocturne-85583080-aa1c-49ca-9469-934d1899d563/styles.css:66
pub const SPACE_2: &str = "5.6px";

/// `space-3` from mockups/_ds/nocturne-85583080-aa1c-49ca-9469-934d1899d563/styles.css:67
pub const SPACE_3: &str = "8.4px";

/// `space-4` from mockups/_ds/nocturne-85583080-aa1c-49ca-9469-934d1899d563/styles.css:68
pub const SPACE_4: &str = "11.2px";

/// `space-6` from mockups/_ds/nocturne-85583080-aa1c-49ca-9469-934d1899d563/styles.css:69
pub const SPACE_6: &str = "16.8px";

/// `space-8` from mockups/_ds/nocturne-85583080-aa1c-49ca-9469-934d1899d563/styles.css:70
pub const SPACE_8: &str = "22.4px";

/// `vk-code-compact` from mockups/assets.md:132
pub const VK_CODE_COMPACT: &str = "12.5px";

/// `vk-code-default` from mockups/assets.md:132
pub const VK_CODE_DEFAULT: &str = "13px";

/// `vk-code-roomy` from mockups/assets.md:132
pub const VK_CODE_ROOMY: &str = "13.5px";

/// `vk-dock-compact` from mockups/assets.md:134
pub const VK_DOCK_COMPACT: &str = "206px";

/// `vk-dock-default` from mockups/assets.md:134
pub const VK_DOCK_DEFAULT: &str = "236px";

/// `vk-dock-roomy` from mockups/assets.md:134
pub const VK_DOCK_ROOMY: &str = "268px";

/// `vk-fs-compact` from mockups/assets.md:131
pub const VK_FS_COMPACT: &str = "12.5px";

/// `vk-fs-default` from mockups/assets.md:131
pub const VK_FS_DEFAULT: &str = "13px";

/// `vk-fs-roomy` from mockups/assets.md:131
pub const VK_FS_ROOMY: &str = "13.5px";

/// `vk-line-compact` from mockups/assets.md:129
pub const VK_LINE_COMPACT: &str = "19px";

/// `vk-line-default` from mockups/assets.md:129
pub const VK_LINE_DEFAULT: &str = "21px";

/// `vk-line-roomy` from mockups/assets.md:129
pub const VK_LINE_ROOMY: &str = "25px";

/// `vk-row-compact` from mockups/assets.md:130
pub const VK_ROW_COMPACT: &str = "22px";

/// `vk-row-default` from mockups/assets.md:130
pub const VK_ROW_DEFAULT: &str = "25px";

/// `vk-row-roomy` from mockups/assets.md:130
pub const VK_ROW_ROOMY: &str = "30px";

/// `vk-tool-compact` from mockups/assets.md:133
pub const VK_TOOL_COMPACT: &str = "250px";

/// `vk-tool-default` from mockups/assets.md:133
pub const VK_TOOL_DEFAULT: &str = "276px";

/// `vk-tool-roomy` from mockups/assets.md:133
pub const VK_TOOL_ROOMY: &str = "310px";

